changed gem name to backtracs and changed shipment serializer
suvie-eng/solidus_backtracs pull request #2
Opened 2022-04-18 14:57 UTC by zeryabkhan91

2022-04-18 15:48 UTC, incorvia requested changes
Let's wait for feedback from Paul at Andlor before proceeding.

2022-04-18 15:48 UTC, incorvia commented on lib/solidus_backtracs/api/shipment_serializer.rb
> +                xml.RMANumber                 @order.number
Let's use the shipment number instead of the order number here as that is specific to the 201R sku that is the refurbed unit.

2022-04-18 15:48 UTC, incorvia commented on lib/solidus_backtracs/api/shipment_serializer.rb
> +                  xml.ShipDate                @shipment.shipped_at&.strftime(SolidusBacktracs::ExportHelper::BACTRACS_DATE_FORMAT)
Open question here: Do we set the ShipDate which I believe is the date we would like this shipped or not. I think not, if this isn't required.

2022-04-18 15:48 UTC, incorvia commented on lib/solidus_backtracs/api/shipment_serializer.rb
> +                      xml.DFItem                  "S020m"
Variant name

2022-04-18 15:48 UTC, incorvia commented on lib/solidus_backtracs/api/shipment_serializer.rb
> +                      xml.DFModelNum              "S020M"
Variant SKU: "SUVIE201R" or "SUVIE201RB"

2022-04-18 15:48 UTC, incorvia commented on lib/solidus_backtracs/api/shipment_serializer.rb
> +                      xml.DFSerialNumbers         @shipment.number
leave this blank

2022-04-18 15:48 UTC, incorvia commented on lib/solidus_backtracs/api/shipment_serializer.rb
> +                      xml.DFCategory              variant.product.name
leave this blank

2022-04-18 15:48 UTC, incorvia commented on lib/solidus_backtracs/api/shipment_serializer.rb
> +                      xml.DFCategoryDescription   variant.product.description
leave this blank

2022-04-18 15:48 UTC, incorvia commented on lib/solidus_backtracs/api/shipment_serializer.rb
> +                      xml.PurchaseDate            line.created_at.strftime(SolidusBacktracs::ExportHelper::BACTRACS_DATE_FORMAT)
order.completed_at

2022-04-18 16:11 UTC, incorvia requested changes

2022-04-18 16:11 UTC, incorvia commented on lib/solidus_backtracs/api/request_runner.rb
> +module SolidusBacktracs
The Backtracs API service requires authenticating through the Authentication before making requests. When we authenticate we need a Username & Password (which should come from ENV variables) and we will receive a sGUID that needs to be included with all requests. Our strategy for authentication should be as follows:

1. We will sign up for QuotaGuard Static IP proxy 
2. We will update HTTParty to use the new proxy service for synces to Backtracs
3. We will cache sGUID that is returned from the authentication service for a configurable amount of time (with a default of 1 hour).
4. When making CreateNew requests we will include the cached sGUID.

2022-04-19 10:32 UTC, zeryabkhan91 commented on app/queries/solidus_backtracs/shipment/pending_api_sync_query.rb
> +          spree_shipments.backtracs_synced_at IS NULL
@incorvia I used `backtracs_synced_at` because the shipments that are send here are queried such that the shipments whose `shipstation_order_id` is not nill means their `shipstation_synced_at` will also be present. So, if we query here `spree_shipments.shipstation_synced_at IS NULL` then no shipments will be forwarded. Do let me know if we need to change here or in the query from `PendingApiSyncQuery`.

2022-04-28 14:27 UTC, closed without merging