modified shipment serializer to work for bundled items
suvie-eng/solidus_backtracs pull request #4
Opened 2022-05-10 11:33 UTC by zeryabkhan91

2022-05-11 14:56 UTC, NewAlexandria commented on lib/generators/solidus_backtracs/install/templates/initializer.rb
> +  config.default_property_name = "XYZ"
is this supposed to be (or somehow _is_) the refurbished property?

2022-05-12 13:47 UTC, NewAlexandria commented on lib/generators/solidus_backtracs/install/templates/initializer.rb
> +  config.default_property_name = "XYZ"
from chat:
> the repo, because it’s a fork, is public, and the refurb code will go public.  security wise, this isn’t really a big deal even though in an ‘absolutelist’ sense, it’s a note of exposure.

2022-05-13 14:55 UTC, incorvia requested changes

2022-05-13 14:55 UTC, incorvia commented on lib/solidus_backtracs/api/shipment_serializer.rb
> +                    if product.assembly?
Let's add: 

```
   product.responds_to?(:assembly?) && product.assembly?
```

2022-05-13 15:46 UTC, NewAlexandria approved these changes

2022-05-13 15:46 UTC, NewAlexandria commented
though this still needs a new gem version.  Did we push it manually the last times?

2022-05-13 15:51 UTC, merged